### ISSUE TITLE
[Respondido] Utilizar o blade em outras aplicações

### ISSUE THREAD

**Issue by rafa-acioly** [artesaos/content-request#14]
# Utilizar o blade em outras aplicações

Como usar/instalar o blade em outras aplicações separadamente do laravel.

**Comment by mauri870** [comment]
É possível utilizar o twig, de certa forma é mais potente em termos de recursos do que o blade, e creio ser mais facilmente integrável

**Comment by vluzrmos** [comment]
É possível

http://themsaid.github.io/katana/

**Comment by vluzrmos** [comment]
Veja que ele só colocou o illuminate/view no composer.json:

https://github.com/themsaid/katana-core/blob/master/composer.json#L15

**Comment by rafa-acioly** [comment]
ja usou esse Katana @vluzrmos ? usar o puramente o blade não é possivel?

**Comment by vinicius73** [comment]
Como apontado pelo @mauri870 é sim @rafa-acioly 
Vc terá q "construi-lo"  manualmente https://github.com/illuminate/view/blob/master/Factory.php#L109

**Comment by tfcdias** [comment]
Utiliza esse repositório, é simples, uso em outros projetos sem Laravel:

https://github.com/jenssegers/blade

**Comment by fhferreira** [comment]
https://github.com/PhiloNL/Laravel-Blade
