### ISSUE TITLE
[Respondido] Como funcionam os "Service" e "Service Provider" e como posso implementar um?

### ISSUE THREAD

**Issue by mprandot** [artesaos/content-request#15]
Qual a relação que eles possuem?
Ele fica disponível em toda a aplicação(Controllers, Models, etc...)?

É uma das poucas coisas (mais complexas) que não consigo implementar com o Laravel, acho que é muito importante, mas infelizmente não sei como funcionam, se puderem me explicar como posso implementar um, ficarei muito grato!

**Comment by vinicius73** [comment]
Atendido: https://medium.com/by-vinicius-reis/laravel-em-profundo-01-wtf-is-service-provider-a9bd817c4a7d
