### ISSUE TITLE
[Respondido] Criar pacote para Laravel com migration

### ISSUE THREAD

**Issue by luizmsilva** [artesaos/content-request#16]
Ola pessoal, gostaria de saber como incuir uma migration em um pacote laravel ?
Se tiver um exemplo melhor ainda.

**Comment by mauri870** [comment]
Boa noite @luizmsilva . Voce pode criar suas migrations normalmente em uma pasta no seu pacote, apos basta publicar elas usando o metodo boot do teu service provider:
```php
$this->publishes([
        __DIR__.'/path/to/migrations' => database_path('migrations/'),
    ]);
```

**Comment by luizmsilva** [comment]
Ok obrigado, vou fazer os teste se der certo ja encerro.

**Comment by fhferreira** [comment]
@luizmsilva @mauri870 tentei responder a esta dúvida: https://medium.com/@f.h.ferreira/criando-packages-com-migrations-no-laravel-5-aa0a1922f365 poderiam dar uma olhada e dar seus feedbacks

**Comment by mauri870** [comment]
@fhferreira Excelente artigo, muito bem explicado parabéns
